#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 01, 2020 02:59:14 PM CST  platform: Windows NT

import sys
import pymysql

try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def comeback():
    destroy_window()
    sys.stdout.flush()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def load_patient():
    patient_name = w.Entry_patientname.get()
    x = w.Treeview.get_children()
    for item in x:
        w.Treeview.delete(item)

    try:
        conn = pymysql.connect(host='localhost', user='myuser', passwd='myuser', db='mydb', port=3306)
        cur = conn.cursor()
        cur.execute("select * FROM patient where patient_name like '%" + patient_name + "%' order by input_time asc")
        rows = cur.fetchall()
        i = 0
        for r1 in rows:
            w.Treeview.insert('', i, values=(r1[0], r1[1], r1[2], r1[3]))
            i += 1
    except pymysql.Error as e:
        print('mysql error %d : %s' % (e.args[0], e.args[1]))
    sys.stdout.flush()

def modify_patient():
    patient_id = w.Label_id['text']
    print('modify patient id ', patient_id)
    patient_name = w.Entry_name.get()
    patient_age = w.Entry_age.get()

    try:
        conn = pymysql.connect(host='localhost', user='myuser', passwd='myuser', db='mydb',port=3306)
        cur = conn.cursor()

        if int(patient_id) == 0:
            cur.execute("insert into patient(patient_name,patient_age,input_time) values(%s,%s,now())",[patient_name,patient_age])
            conn.commit()
            if cur.rowcount == 1:
                v.showinfo(patient_name, "病人信息保存成功")
            else:
                v.showerror(patient_name, "病人信息保存失败")
        else:
            cur.execute("update patient set patient_name='" + patient_name + "' , patient_age=" + patient_age + " , input_time=now() where patient_id="+ patient_id)
            conn.commit()
            if cur.rowcount == 1:
                v.showinfo(patient_name, "病人信息修改成功")
            else:
                v.showerror(patient_name, "病人信息修改失败")

        cur.close()
        conn.close()

    except pymysql.Error as e:
        print('mysql error %d : %s' % (e.args[0],e.args[1]))
    sys.stdout.flush()
    load_patient()

def add_patient():
    text1 = "0"
    text2 = ""
    text4 = "20"
    w.Label_id.configure(text=text1)
    w.Entry_name.delete(first=0, last='end')
    w.Entry_name.insert(0, text2)
    w.Entry_age.delete(first=0, last='end')
    w.Entry_age.insert(0, text4)
    v.showinfo(text1, "请填写姓名和年龄，再点保存")

def delete_patient():
    patient_id = w.Label_id['text']
    print('modify patient id ', patient_id)
    patient_name = w.Entry_name.get()
    patient_age = w.Entry_age.get()
    try:
        conn = pymysql.connect(host='localhost', user='myuser', passwd='myuser', db='mydb', port=3306)
        cur = conn.cursor()

        cur.execute(
            "delete from patient where patient_id=" + patient_id)

        conn.commit()
        if cur.rowcount == 1:
            v.showinfo(patient_name, "病人信息删除成功")
        else:
            v.showerror(patient_name, "病人信息删除失败")

        cur.close()
        conn.close()

    except pymysql.Error as e:
        print('mysql error %d : %s' % (e.args[0], e.args[1]))
    sys.stdout.flush()
    load_patient()

if __name__ == '__main__':
    import patient_admin
    patient_admin.vp_start_gui()
