# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\source\repos\PythonApplication_ST1\login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial

class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(466, 639)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 100, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 240, 54, 12))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 290, 54, 12))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.input_uid = QtWidgets.QLineEdit(self.centralwidget)
        self.input_uid.setGeometry(QtCore.QRect(160, 240, 171, 20))
        self.input_uid.setObjectName("input_uid")
        self.input_passwd = QtWidgets.QLineEdit(self.centralwidget)
        self.input_passwd.setGeometry(QtCore.QRect(160, 280, 171, 20))
        self.input_passwd.setObjectName("input_passwd")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(160, 330, 171, 31))
        self.btn_login.setCheckable(False)
        self.btn_login.setFlat(False)
        self.btn_login.setObjectName("btn_login")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "登录"))
        self.label.setText(_translate("LoginWindow", "宾馆餐饮管理系统"))
        self.label_2.setText(_translate("LoginWindow", "工号"))
        self.label_3.setText(_translate("LoginWindow", "密码"))
        self.btn_login.setText(_translate("LoginWindow", "登录"))
        self.input_uid.setText("admin")
        self.input_passwd.setText("admin")

