# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Spec_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(488, 359)
        self.btn_prev_spec = QtWidgets.QPushButton(Form)
        self.btn_prev_spec.setGeometry(QtCore.QRect(80, 20, 75, 23))
        self.btn_prev_spec.setObjectName("btn_prev_spec")
        self.label_rowno_cc = QtWidgets.QLabel(Form)
        self.label_rowno_cc.setGeometry(QtCore.QRect(180, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_rowno_cc.setFont(font)
        self.label_rowno_cc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rowno_cc.setObjectName("label_rowno_cc")
        self.btn_next_spec = QtWidgets.QPushButton(Form)
        self.btn_next_spec.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.btn_next_spec.setObjectName("btn_next_spec")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 371, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(240, 80, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(350, 80, 71, 16))
        self.label_5.setObjectName("label_5")
        self.input_spec_no = QtWidgets.QLineEdit(Form)
        self.input_spec_no.setGeometry(QtCore.QRect(80, 80, 141, 20))
        self.input_spec_no.setObjectName("input_spec_no")
        self.input_status = QtWidgets.QLineEdit(Form)
        self.input_status.setGeometry(QtCore.QRect(290, 80, 41, 20))
        self.input_status.setObjectName("input_status")
        self.input_spec_active = QtWidgets.QLineEdit(Form)
        self.input_spec_active.setGeometry(QtCore.QRect(420, 80, 41, 20))
        self.input_spec_active.setObjectName("input_spec_active")
        self.input_goods_spec = QtWidgets.QLineEdit(Form)
        self.input_goods_spec.setGeometry(QtCore.QRect(80, 110, 381, 20))
        self.input_goods_spec.setObjectName("input_goods_spec")
        self.label_spec_logo = QtWidgets.QLabel(Form)
        self.label_spec_logo.setGeometry(QtCore.QRect(20, 150, 151, 141))
        self.label_spec_logo.setFrameShape(QtWidgets.QFrame.Box)
        self.label_spec_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spec_logo.setObjectName("label_spec_logo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_prev_spec.setText(_translate("Form", "上一个"))
        self.label_rowno_cc.setText(_translate("Form", "（1/4）"))
        self.btn_next_spec.setText(_translate("Form", "下一个"))
        self.label_2.setText(_translate("Form", "SpecNo"))
        self.label_3.setText(_translate("Form", "GoodsSpec"))
        self.label_4.setText(_translate("Form", "status"))
        self.label_5.setText(_translate("Form", "specActive"))
        self.label_spec_logo.setText(_translate("Form", "logo"))
