# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spider.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(856, 653)
        self.pushButton_query = QtWidgets.QPushButton(Form)
        self.pushButton_query.setGeometry(QtCore.QRect(740, 30, 75, 23))
        self.pushButton_query.setObjectName("pushButton_query")
        self.pushButton_send = QtWidgets.QPushButton(Form)
        self.pushButton_send.setGeometry(QtCore.QRect(750, 570, 75, 23))
        self.pushButton_send.setObjectName("pushButton_send")
        self.lineEdit_query_in = QtWidgets.QLineEdit(Form)
        self.lineEdit_query_in.setGeometry(QtCore.QRect(20, 30, 211, 20))
        self.lineEdit_query_in.setObjectName("lineEdit_query_in")
        self.lineEdit_query_not = QtWidgets.QLineEdit(Form)
        self.lineEdit_query_not.setGeometry(QtCore.QRect(250, 30, 211, 20))
        self.lineEdit_query_not.setObjectName("lineEdit_query_not")
        self.dateEdit_begin = QtWidgets.QDateEdit(Form)
        self.dateEdit_begin.setGeometry(QtCore.QRect(480, 30, 110, 22))
        self.dateEdit_begin.setObjectName("dateEdit_begin")
        self.dateEdit_end = QtWidgets.QDateEdit(Form)
        self.dateEdit_end.setGeometry(QtCore.QRect(610, 30, 110, 22))
        self.dateEdit_end.setObjectName("dateEdit_end")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 60, 811, 491))
        self.widget.setObjectName("widget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_query.setText(_translate("Form", "query"))
        self.pushButton_send.setText(_translate("Form", "send"))
